project/slaves/urls.py
from django.urls import re_path
from project.slaves import views

urlpatterns = [
    re_path('^$', views.index_view, name='index'),
    re_path('^create/$', views.creates_view, name='create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('project.slaves.urls', 'index'), namespace='slaves')),
    path('admin/', admin.site.urls),
]

project/slaves/models.py
from django.contrib.auth.models import User
from django.db import models


class Resume(models.Model):
    objects = None
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец')
    title = models.CharField('Название', max_length=128)
    money = models.PositiveIntegerField('Желаемая зарплата')
    skills = models.TextField('Навыки', help_text='Напиши все что умеешь')
    education = models.CharField('Образование', max_length=1024, blank=True, null=True)
    registered_in = models.DateTimeField('Создано', auto_now_add=True)

    def __str__(self):
        return f'{self.title} {self.money}'


class Place(models.Model):
    """Описывает место работы раба"""
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, verbose_name='Резюме')
    title = models.CharField(verbose_name='работодатель', max_length=128)
    position = models.CharField(verbose_name='должность', max_length=128)
    duty = models.TextField('Обязанности', blank=True, null=True)
    started_in = models.DateField('Начал работать')
    finished_in = models.DateField('Закончил работать', blank=True, null=True)
    registered_in = models.DateTimeField('Создано', auto_now_add=True)

    def __str__(self):
        return f'{self.title} {self.position}'

project/slaves/forms.py
from django import forms

from project.slaves import models


class ResumeForms(forms.ModelForm):
    class Meta:
        model = models.Resume
        exclude = ('owner', 'registered_in', )

    def save(self, user):
        obj = super().save(commit=False)
        obj.owner = user
        return obj.save()

project/slaves/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from project.slaves.models import Resume
from project.slaves.forms import ResumeForms


def index_view(request):
    """Вьюха отображает главную страницу приложения"""
    qs = Resume.objects.all()
    context = {
        'title': 'Твой путь к успеху',
        'queryset': qs,
        }
    return render(request, 'slaves/index.html', context)


def creates_view(request):
    """ Показывает или обрабатывает форму """
    form = ResumeForms(request.POST or None)
    context = {
        'title': 'Новое резюме',
        'form': form,
        }
    if request.method == 'POST' and form.is_valid():
        form.save(request.user)
        return redirect('slaves:index')
    return render(request, 'slaves/create.html', context)

project/slaves/templates/slaves/create.html
<html lang="ru">{% load bootstrap5 %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{{ title }}</title>

</head>

<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="https://bootstrap-4.ru/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">Work in Russia</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Создать</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
<main class="flex-shrink-0">
    <div class="container-fluid">
      <h1>{{ title }}</h1>
    </div>
    <div class="container-fluid">
        <h2>Новое резюме</h2>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm">
            <form method="post" action="{% url 'slaves:create' %}" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Отправить</button>
                {% endbuttons %}
            </form>
        </div>
        <div class="col-sm">
          Один из трех столбцов
        </div>
      </div>
    </div>

</main>

    <footer class="footer mt-auto py-3 bg-dark">
      <div class="container-fluid">
        <span class="text-muted">© 2024 ООО «Work in Russia».</span>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

project/slaves/templates/slaves/index.html
<html lang="ru">{% load bootstrap5 %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{{ title }}</title>

</head>

<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="https://bootstrap-4.ru/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">Work in Russia</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Создать</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
<main class="flex-shrink-0">
    <div class="container-fluid">
      <h1>{{ title }}</h1>
      <p>List of Slaves</p>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Владелец</th>
                <th scope="col">Название</th>
                <th scope="col">Заработная плата</th>
                <th scope="col">Дата регистрации</th>
            </tr>
        </thead>
        <tbody>
            {% for item in queryset %}
            <tr>
                <td>{{ item.owner }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.money }}</td>
                <td>{{ item.registered_in }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    </hr>

    <div class="container-fluid">
        <h2>Новое резюме</h2>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm">
            <form method="post" action="{% url 'slaves:index' %}" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Отправить</button>
                {% endbuttons %}
            </form>
        </div>
        <div class="col-sm">
          Один из трех столбцов
        </div>
      </div>
    </div>

</main>

    <footer class="footer mt-auto py-3 bg-dark">
      <div class="container-fluid">
        <span class="text-muted">© 2024 ООО «Work in Russia».</span>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>